language: php
php:
  - 7.1.9
before_script:
  - composer install
script:
  - phpunit --no-coverage indexTest.php
deploy:
  provider: heroku
  api_key:
    secure: N4idtmFSs28jL3eAgLvVL0QtLPh0rbauQC1xXgw8XBcQgqyJnxuH4uY+eT+UjE1RM/8jYM5xh207tqEIgLPyKTIM0lvIefD2SLSeeuk4sBYlqZrzfJeOwGg9dYkOstz2eCWPRmdwFWLfvGBbZ2lbJwUJUv652J+TSINu7sloWkZmLgk7w0uct6s7OUHPFDHrTcSoo0inkIhSGYELatNuGovEcmqrQro1ID2Z3+5HBGNNamWezeAZ4pFY2ZqmsNehIhqNN9bjMUfCMrRfcekZsC35/dziJl4iYU2xAjP3n04f8e2NOLZw/qYAG059R1qsjUGaWzofv4pCgRlBpAPip4VAN0Qv5B8lRX9knGHRY89Ftl5Z85pPjS3ClpM7WOQrm1JnD1R5mLQiXVQTNbvm8GzUF1bzVdTfxZSHGlAidSb0/XXjL2OAywqZjU2cBQxF/u8JJHomXsj0bRGWSndRLX4JwCzf7CnMgg/pgSxNHvNmcGukms2ANpuENp/gX5qTlgDD3IjxC9DJyxW2bBoNaxICTK0H9XOacZ1oUyJn84EPBo1uvOZahzawR+5UtbwHoHXTxwkdqcTS/k0zV16CmLRa1+Cg1Ayq+aekOqEGbV/1xyrIwOmroYDdRSJuAAio74G5PFhLk0y/qReVvE+314r1Cq18a0Mo5pCj4Qy8BcQ=
    master: devops-stt30
